# fly.toml file generated for blue-dawn-4985 on 2022-09-24T20:38:22+02:00

app = "blue-dawn-4985"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "udp"

  [[services.ports]]
    port = "8080"
